package com.cuius.web.cuius_web.entity;
// Generated Jan 20, 2019 7:12:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductOrder generated by hbm2java
 */
@Entity
@Table(name="product_order"
    ,catalog="project_cuius"
)
public class ProductOrder  implements java.io.Serializable {


     private Integer orderId;
     private Customers customers;
     private Product product;
     private int merchantId;
     private int deliveryId;
     private Date orderDate;
     private int orderQty;
     private double totalPrice;
     private String orderStatus;
     private Set productOrderDetailses = new HashSet(0);

    public ProductOrder() {
    }

	
    public ProductOrder(Customers customers, Product product, int merchantId, int deliveryId, Date orderDate, int orderQty, double totalPrice, String orderStatus) {
        this.customers = customers;
        this.product = product;
        this.merchantId = merchantId;
        this.deliveryId = deliveryId;
        this.orderDate = orderDate;
        this.orderQty = orderQty;
        this.totalPrice = totalPrice;
        this.orderStatus = orderStatus;
    }
    public ProductOrder(Customers customers, Product product, int merchantId, int deliveryId, Date orderDate, int orderQty, double totalPrice, String orderStatus, Set productOrderDetailses) {
       this.customers = customers;
       this.product = product;
       this.merchantId = merchantId;
       this.deliveryId = deliveryId;
       this.orderDate = orderDate;
       this.orderQty = orderQty;
       this.totalPrice = totalPrice;
       this.orderStatus = orderStatus;
       this.productOrderDetailses = productOrderDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_id", unique=true, nullable=false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pro_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="merchant_id", nullable=false)
    public int getMerchantId() {
        return this.merchantId;
    }
    
    public void setMerchantId(int merchantId) {
        this.merchantId = merchantId;
    }

    
    @Column(name="delivery_id", nullable=false)
    public int getDeliveryId() {
        return this.deliveryId;
    }
    
    public void setDeliveryId(int deliveryId) {
        this.deliveryId = deliveryId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="order_date", nullable=false, length=10)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="order_qty", nullable=false)
    public int getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(int orderQty) {
        this.orderQty = orderQty;
    }

    
    @Column(name="total_price", nullable=false, precision=22, scale=0)
    public double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    
    @Column(name="order_status", nullable=false, length=45)
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productOrder")
    public Set getProductOrderDetailses() {
        return this.productOrderDetailses;
    }
    
    public void setProductOrderDetailses(Set productOrderDetailses) {
        this.productOrderDetailses = productOrderDetailses;
    }




}


