package com.cuius.web.cuius_web.entity;
// Generated Jan 20, 2019 7:12:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductOrderDetails generated by hbm2java
 */
@Entity
@Table(name="product_order_details"
    ,catalog="project_cuius"
)
public class ProductOrderDetails  implements java.io.Serializable {


     private Integer orderDetId;
     private Product product;
     private ProductOrder productOrder;
     private int proQty;

    public ProductOrderDetails() {
    }

    public ProductOrderDetails(Product product, ProductOrder productOrder, int proQty) {
       this.product = product;
       this.productOrder = productOrder;
       this.proQty = proQty;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="order_det_id", unique=true, nullable=false)
    public Integer getOrderDetId() {
        return this.orderDetId;
    }
    
    public void setOrderDetId(Integer orderDetId) {
        this.orderDetId = orderDetId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pro_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public ProductOrder getProductOrder() {
        return this.productOrder;
    }
    
    public void setProductOrder(ProductOrder productOrder) {
        this.productOrder = productOrder;
    }

    
    @Column(name="pro_qty", nullable=false)
    public int getProQty() {
        return this.proQty;
    }
    
    public void setProQty(int proQty) {
        this.proQty = proQty;
    }




}


