package com.cuius.web.cuius_web.entity;
// Generated Jan 20, 2019 7:12:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * SubCategory generated by hbm2java
 */
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name="sub_category"
    ,catalog="project_cuius"
)
public class SubCategory  implements java.io.Serializable {


     private Integer subCatId;
     private Category category;
     private String subCatName;
     private String subCatDesc;
     private Set products = new HashSet(0);

    public SubCategory() {
    }

	
    public SubCategory(Category category, String subCatName, String subCatDesc) {
        this.category = category;
        this.subCatName = subCatName;
        this.subCatDesc = subCatDesc;
    }
    public SubCategory(Category category, String subCatName, String subCatDesc, Set products) {
       this.category = category;
       this.subCatName = subCatName;
       this.subCatDesc = subCatDesc;
       this.products = products;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sub_cat_id", unique=true, nullable=false)
    public Integer getSubCatId() {
        return this.subCatId;
    }
    
    public void setSubCatId(Integer subCatId) {
        this.subCatId = subCatId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cat_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="sub_cat_name", nullable=false, length=250)
    public String getSubCatName() {
        return this.subCatName;
    }
    
    public void setSubCatName(String subCatName) {
        this.subCatName = subCatName;
    }

    
    @Column(name="sub_cat_desc", nullable=false, length=2000)
    public String getSubCatDesc() {
        return this.subCatDesc;
    }
    
    public void setSubCatDesc(String subCatDesc) {
        this.subCatDesc = subCatDesc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subCategory")
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


