package com.cuius.web.cuius_web.entity;
// Generated Jan 20, 2019 7:12:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TransactionLog generated by hbm2java
 */
@Entity
@Table(name="transaction_log"
    ,catalog="project_cuius"
)
public class TransactionLog  implements java.io.Serializable {


     private Integer logId;
     private int customerId;
     private String fullNameOnCc;
     private String firstName;
     private String lastName;
     private String addressLine1;
     private String addressLine2;
     private String email;
     private String city;
     private String country;
     private String phone;
     private String pan;
     private String expirationDate;
     private String transationAmount;
     private String transactionDateAndTime;

    public TransactionLog() {
    }

	
    public TransactionLog(int customerId, String fullNameOnCc, String firstName, String lastName, String addressLine1, String email, String country, String phone, String pan, String expirationDate, String transationAmount, String transactionDateAndTime) {
        this.customerId = customerId;
        this.fullNameOnCc = fullNameOnCc;
        this.firstName = firstName;
        this.lastName = lastName;
        this.addressLine1 = addressLine1;
        this.email = email;
        this.country = country;
        this.phone = phone;
        this.pan = pan;
        this.expirationDate = expirationDate;
        this.transationAmount = transationAmount;
        this.transactionDateAndTime = transactionDateAndTime;
    }
    public TransactionLog(int customerId, String fullNameOnCc, String firstName, String lastName, String addressLine1, String addressLine2, String email, String city, String country, String phone, String pan, String expirationDate, String transationAmount, String transactionDateAndTime) {
       this.customerId = customerId;
       this.fullNameOnCc = fullNameOnCc;
       this.firstName = firstName;
       this.lastName = lastName;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.email = email;
       this.city = city;
       this.country = country;
       this.phone = phone;
       this.pan = pan;
       this.expirationDate = expirationDate;
       this.transationAmount = transationAmount;
       this.transactionDateAndTime = transactionDateAndTime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="log_id", unique=true, nullable=false)
    public Integer getLogId() {
        return this.logId;
    }
    
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    
    @Column(name="customer_id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="full_name_on_cc", nullable=false, length=50)
    public String getFullNameOnCc() {
        return this.fullNameOnCc;
    }
    
    public void setFullNameOnCc(String fullNameOnCc) {
        this.fullNameOnCc = fullNameOnCc;
    }

    
    @Column(name="first_name", nullable=false, length=100)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=100)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="address_line1", nullable=false, length=100)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="address_line2", length=100)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="city", length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="country", nullable=false, length=50)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="phone", nullable=false, length=50)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="PAN", nullable=false, length=100)
    public String getPan() {
        return this.pan;
    }
    
    public void setPan(String pan) {
        this.pan = pan;
    }

    
    @Column(name="expiration_date", nullable=false, length=4)
    public String getExpirationDate() {
        return this.expirationDate;
    }
    
    public void setExpirationDate(String expirationDate) {
        this.expirationDate = expirationDate;
    }

    
    @Column(name="transation_amount", nullable=false, length=16)
    public String getTransationAmount() {
        return this.transationAmount;
    }
    
    public void setTransationAmount(String transationAmount) {
        this.transationAmount = transationAmount;
    }

    
    @Column(name="transaction_date_and_time", nullable=false, length=50)
    public String getTransactionDateAndTime() {
        return this.transactionDateAndTime;
    }
    
    public void setTransactionDateAndTime(String transactionDateAndTime) {
        this.transactionDateAndTime = transactionDateAndTime;
    }




}


